Repository PinTogether/frontend, pull requests merged in 2024-02, with the labels that each got.

#11 Fix/fix warnning #10
  next.config.mjs
  src/app/(popup)/popup/page.tsx
  src/app/cardslide/page.tsx
  src/components/CardSlider.tsx
  src/containers/layout/Sidebar.tsx
  src/containers/popup/LoginPopup.tsx
Labels: bug, frontend

#17 Design/ collection, profile page 구현 #16
  public/icon/edit_plain.svg
  src/app/(default)/collection/page.tsx
  src/app/(default)/profile/page.tsx
  src/containers/layout/Maincontent.tsx
  src/containers/layout/Sidebar.tsx
  src/styles/layout/_collectionPage.module.scss
  src/styles/layout/_maincontent.module.scss
  src/styles/layout/_profilePage.module.scss
Labels: frontend, design

#18 Feature&Desgin/card components #12
  public/icon/link_plain.svg
  public/icon/pin.svg
  public/images/food_dummy.jpg
  public/images/food_dummy2.jpg
  src/app/(default)/(example)/cardcomponents/page.tsx
  src/app/(default)/(example)/cardslide/page.tsx
  src/app/(default)/login/page.tsx
  src/components/Button.tsx
  src/components/Comment.tsx
  src/components/Header.tsx
  src/components/Icons.tsx
  src/components/PinCard.tsx
  src/styles/base/_placeholders.scss
  src/styles/base/_variables.scss
  src/styles/components/_comment.module.scss
  src/styles/components/_pincard.module.scss
Labels: enhancement, frontend, design
